CREATE TABLE "MATCHS"(
    "ID" BIGINT PRIMARY KEY,
    "DATE" DATE NOT NULL,
    "OPPONENT" VARCHAR(30) NOT NULL,
    "SPARTA_GOALS" INTEGER NOT NULL,
    "OPPONET_GOALS" INTEGER NOT NULL,
    "SPARTA_SHOTS" INTEGER NOT NULL,
    "OPPONET_SHOTS" INTEGER NOT NULL,
    "SPARTA_PENALTY" INTEGER NOT NULL,
    "OPPONET_PENALTY" INTEGER NOT NULL,
    "HOME" VARCHAR(30) NOT NULL,
    "BEST_PLAYER" VARCHAR(30) NOT NULL);

CREATE TABLE "PLAYERS" (
    "PLAYERID" INT PRIMARY KEY,
    "NAME" VARCHAR(30) NOT NULL,
    "AGE" INTEGER,
    "HEIGHT" INTEGER,
    "WEIGHT" INTEGER,
    "PLAYERNUM" INTEGER,
    "POSITION" INTEGER);

CREATE TABLE "STATS" (
    PLAYERID INT,
    MATCHID INT,
    GOALS INT,
    ASSISTS INT,
    PENALTY_MINUTES INT,
    SHOTS INT,
    HITS INT);

CREATE TABLE "GOAL" (
    "ID" BIGINT ,
    "MATCHS" BIGINT NOT NULL ,
    "PLAYER" VARCHAR(20) NOT NULL,
    "MINIT" INTEGER NOT NULL);

CREATE TABLE "ASSIST" (
    "ID" BIGINT PRIMARY KEY,
    "MATCHS" BIGINT NOT NULL,
    "PLAYER" VARCHAR(20) NOT NULL,
    "GOAL" BIGINT NOT NULL );

CREATE TABLE "PLAYED" (
    "MATCHS" BIGINT NOT NULL ,
    "PLAYER" VARCHAR(20));
